runtime: java17
instance_class: F2
env: standard

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  SPRING_DATASOURCE_URL: jdbc:mysql://google/clientlogindb?cloudSqlInstance=clientapp-441220:us-east1:clientlogindb&socketFactory=com.google.cloud.sql.mysql.SocketFactory
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: (/u>ji;~E3Rm2@1h
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"

handlers:
  - url: /api/.*  # Specify backend API routes
    script: auto  # Routes that are handled by the backend

  - url: /.*  # This catches all other routes
    static_files: build/index.html  # Serve React app's entry point
    upload: build/index.html
    secure: always
