steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
        mvn clean build
